dist: xenial
os: osx
language: minimal
arch: amd64
# https://docs.travis-ci.com/user/reference/osx/#macos-version
osx_image: xcode11.3
env:
  global:
    - DASHCORE_VERSION=0.15.0.0
    - ORIGINAL_HASH=09f76396217eef6e5a7ba464d9b1f5abd78925b314f663bb709fdb02013899df
    - EXPECTED_HASH=9fe20cbbb3050be5dc0db2b900ab0772395ffcd47679d0769158146febfacdc3
script:
  - wget https://github.com/dashpay/dash/releases/download/v$DASHCORE_VERSION/dashcore-$DASHCORE_VERSION-osx.dmg
  - export DOWNLOADED_HASH=$(shasum -a 256 dashcore-$DASHCORE_VERSION-osx.dmg | awk '{print $1;}')
  - echo "ORIGINAL_HASH    = $ORIGINAL_HASH"; echo "DOWNLOADED_HASH  = $DOWNLOADED_HASH"
  - if [ "$ORIGINAL_HASH" != "$DOWNLOADED_HASH" ]; then echo "Downloaded file does not match the original one!"; false; fi
  - xcrun stapler staple dashcore-$DASHCORE_VERSION-osx.dmg
  - export STAPLED_HASH=$(shasum -a 256 dashcore-$DASHCORE_VERSION-osx.dmg | awk '{print $1;}')
  - echo "EXPECTED_HASH    = $EXPECTED_HASH"; echo "STAPLED_HASH     = $STAPLED_HASH"
  - if [ "$EXPECTED_HASH" != "$STAPLED_HASH" ]; then echo "Stapled file does not match the expected result!"; false; fi
